### ISSUE TITLE
Launcher (Web Server): Invalid request (Unexpected EOF)

### ISSUE THREAD

**Issue by lukas-k** [TWLan/Issues#103]
The launcher (Web Server) reports the message "Invalid request (Unexpected EOF)" every ~10 seconds during the game (village overview) is opened in browser (1 player, no active game play). I'm using the Mozilla Firefox 38 for Linux Mint (32 bit).
![twlan-x86mint-invalidrequest](https://cloud.githubusercontent.com/assets/13632429/9250007/0dc2be9c-41ca-11e5-9536-6922017f070e.png)
After logging out and closing the tab in browser, the launcher stops sending the "invalid request" messages.

**Comment by steffengy** [comment]
The error message is accurate since (probably) firefox tries to establish a connection
using keep-alive, which tries to reuse a http connection for later requests, which then
after a specific timeout looks like no content (->EOF) for the server.

https://bugs.php.net/bug.php?id=69426
https://bugs.php.net/bug.php?id=60471

Not a direct problem of the TWLan but just an unsupported/not properly supported feature
of the internal PHP webserver, which causes no harm but a bit annoying output.

**Comment by Siguza** [comment]
Maybe filter that error message in the launcher?

**Comment by ShounPL** [comment]
Sorry for my English, try using a different browser Google Chrome, or similar, as it does not work, change the port Laucher for example, in 8000, I explained to google translator

**Comment by 0xEAB** [comment]
Looks like this one has been fixed: https://github.com/php/php-src/pull/2442

**Comment by chintanvadi** [comment]
invalid request (unexpected eof) laravel?
