### ISSUE TITLE
Resources per Minute instead of hour

### ISSUE THREAD

**Issue by halliba** [TWLan/Issues#107]
In original Speed worlds, the Recources are displayed per Minute and not per hour. 
You could Display it depending on Speed or make it an Option in Settings.

**Comment by Siguza** [comment]
This is actually already being done (in TWLan/htdocs/templates/twlan/controllers/game/overview/prod.php), but I just realised the check for switching to minutes is broken and will never run.
Will be fixed in the next release, for now you can replace `elseif($prod >= 600000)` by `elseif($prod >= 10000)`, if you want.
But I'll mark the "make a setting for this" as a feature request.
